---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flask-app-for-autoscaling
  namespace: python-demo-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: sample-flask-app
        image: wolfycodes4fun/python-sample-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
# Exposing the application with a service
apiVersion: v1
kind: Service
metadata:
  name: demo-flask-app-for-autoscaling-service
  namespace: python-demo-app
  labels:
    app: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  type: LoadBalancer

---
# ServiceMonitor for Prometheus to scrape metrics from the application
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-flask-app-for-autoscaling-monitor
  namespace: python-demo-app
  labels:
    app: flask-app
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: flask-app-service
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
